spring.datasource.url=jdbc:mysql://localhost:3306/ngo_transparency
spring.datasource.username=root
spring.datasource.password=radha27031978@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
server.port=8080
